services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cloudpock3t_p4ss
      POSTGRES_DB: cloudpocket
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: cloudpock3t_p4ss
      DB_NAME: cloudpocket
      JWT_SECRET: your-super-secret-jwt-key

volumes:
  postgres_data: